// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomsNest.DataAccess.Data;

#nullable disable

namespace MomsNest.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240202052954_Productstodb")]
    partial class Productstodb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomsNest.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Footwear"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Toys"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            Name = "Hygiene"
                        });
                });

            modelBuilder.Entity("MomsNest.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "SnuggleCo",
                            CategoryID = 2,
                            Color = "Brown",
                            Description = "Soft and cuddly teddy bear for newborns",
                            Material = "Plush",
                            Price = 19.99m,
                            ProductName = "Cuddly Teddy Bear",
                            StockQuantity = 50,
                            Weight = 0.5m
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "TinyTots",
                            CategoryID = 2,
                            Color = "Pastel",
                            Description = "Adorable onesie set for infants",
                            Material = "Cotton",
                            Price = 29.99m,
                            ProductName = "Baby Onesie Set",
                            StockQuantity = 30,
                            Weight = 0.3m
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "PlayfulHands",
                            CategoryID = 2,
                            Color = "Multicolor",
                            Description = "Colorful mobile with music for crib entertainment",
                            Material = "Plastic",
                            Price = 39.99m,
                            ProductName = "Interactive Baby Mobile",
                            StockQuantity = 20,
                            Weight = 0.8m
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "MunchieMunch",
                            CategoryID = 2,
                            Color = "Blue",
                            Description = "Complete feeding set for infants",
                            Material = "BPA-Free Plastic",
                            Price = 49.99m,
                            ProductName = "Baby Feeding Set",
                            StockQuantity = 25,
                            Weight = 0.6m
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "LearnSmart",
                            CategoryID = 2,
                            Color = "Yellow",
                            Description = "Interactive and colorful book for early learning",
                            Material = "Cardboard",
                            Price = 14.99m,
                            ProductName = "Educational Baby Book",
                            StockQuantity = 40,
                            Weight = 0.2m
                        });
                });

            modelBuilder.Entity("MomsNest.Models.Product", b =>
                {
                    b.HasOne("MomsNest.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
